### ISSUE TITLE
Po aktualizacji HA do 2021.12 Import error and warning 

### ISSUE THREAD

**Issue by snp88** [KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym#23]
Hej Krzysztof 

Wydaje mi się ze po ostatniej aktualizacji zaszły spore zmiany w Python-miio
I kiedy używam twojego komponentu reszta urządzeń xiaomi przestaje działać 
zmieniłem w manifescie wersje biblioteki z 5.8 na 5.9.1 

Błedy kiedy używam biblioteki miio w wersji 5.8
![image](https://user-images.githubusercontent.com/46537540/145787422-03a9653d-6316-46ac-b344-f0505f34ef2d.png)
![image](https://user-images.githubusercontent.com/46537540/145787525-18799da4-787f-49ec-ad66-0f86ef23c1cc.png)

po "aktualizacji" biblioteki zostaje tylko
![image](https://user-images.githubusercontent.com/46537540/145788192-5e95070e-b278-4b02-b0f9-12ad32cb2362.png)

Daj znać czy potrzebujesz jakiś dodatkowych informacji

**Comment by snp88** [comment]
Hej @KrzysztofHajdamowicz 
zerknij tutaj 
https://github.com/rytilahti/python-miio/issues/1240 na komentarz od rytilahti
da sie sfixowac repo zeby nie dostawać tych warnningów :)?

**Comment by snp88** [comment]
Podejrzewam ze trzeba zmienic klase z Vacuum na ViomiVacuum

**Comment by KrzysztofHajdamowicz** [comment]
Hi, sorry for late reply. It's fixed in recent release.
