### ISSUE TITLE
HA 2021.12.2 warnings

### ISSUE THREAD

**Issue by va77** [KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym#24]
Hi.
2021-12-18 18:29:27 WARNING (MainThread) [homeassistant.helpers.entity] Entity vacuum.pylesos (<class 'custom_components.miio2.vacuum.MiroboVacuum2'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by va77** [comment]
Any update related to this warning?

**Comment by mrwogu** [comment]
+1

**Comment by va77** [comment]
Any update ?

**Comment by Mick51** [comment]
Any update ?

**Comment by carvalr** [comment]
Just update the file vacuum.py and replace the function name from "device_state_attributes" to "extra_state_attributes" and restart HA.

![image](https://user-images.githubusercontent.com/74059823/152662842-04255d4e-57d1-4885-819e-2e125decec5b.png)

**Comment by KrzysztofHajdamowicz** [comment]
Hi, sorry for late reply. It's fixed in recent release.
