### ISSUE TITLE
Can not be found in hacs store.

### ISSUE THREAD

**Issue by zjn9011** [KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym#27]
I cant find any plugin named "styj02m" or "vacuum-styj2m" in HACS store.
You also can reproduce this issue in [hacs-repositories](https://hacs-repositories.web.app/),and can not find any plugin relating to this github repository.
PLEASE check it out!

**Comment by rgomezgar** [comment]
Hey! try to add the repository url (https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym) into "custom repositories" in HACS (https://hacs.xyz/docs/faq/custom_repositories)
This repo is not listed by default

**Comment by zjn9011** [comment]
> Hey! try to add the repository url (https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym) into "custom repositories" in HACS (https://hacs.xyz/docs/faq/custom_repositories) This repo is not listed by default

Thank you very much! Your comment has resolved my problem!
DELIVER MY BEST RESPECT FROM CHINA!
