### ISSUE TITLE
Error: Integration 'miio2' not found.

### ISSUE THREAD

**Issue by INPoppoRTUNE** [KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym#35]
I'm having a little bit of a trouble installing this repository:
- I have HACS installed.
- I installed the custom repository through HACS: 
![immagine](https://user-images.githubusercontent.com/23138929/176708857-de19abb3-45c1-43a2-adee-25ce5afbf692.png)
- I recovered the token and added the given configuration to configuration.yaml
- I tryed to restart the server but it return the following error: `The system cannot restart because the configuration is not valid: Platform error vacuum.miio2 - Integration 'miio2' not found.`

[Complete log dump](https://pastebin.com/raw/WnYxSc3D).

What am I missing?

**Comment by jeremysherriff** [comment]
Install the integration via HACS, then reboot before you create the yaml configuration.

**Comment by INPoppoRTUNE** [comment]
> Install the integration via HACS, then restart HA before you create the yaml configuration.

Server restart fine without the yaml config part, but won't restart after re-adding it, returning the same error.

**Comment by jeremysherriff** [comment]
Glad it got sorted!
