### ISSUE TITLE
Update miio

### ISSUE THREAD

**Issue by pticavorobey** [KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym#39]
Hello my friend.
Your wonderful component uses a very old version of miio. I would like to ask you to update it to the current one. The fact is that a situation arises in which other integrations, no less remarkable than yours, stop working. Here is one such example https://github.com/syssi/xiaomi_airpurifier/issues/296

**Comment by KrzysztofHajdamowicz** [comment]
Hello!

This integration is abandoned right now, but new maintainer will be welcomed!
