### ISSUE TITLE
did it stop working with the latest HA update?

### ISSUE THREAD

**Issue by sheminasalam** [KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym#47]
I have been using it for a long time but now after the latest update, this integration is not able to find my vacuum. It is not creating the vacuum entity also. What's happening?

**Comment by sheminasalam** [comment]
can anybody help me sort this?

**Comment by DominikWrobel** [comment]
Have the same problem, after 2024.2 the integration is not working, my guess is the python upgrade broke the integration.

**Comment by InfernoJaffa** [comment]
Just delete the version checks within manifest.json

From
` "requirements": [
    "construct==2.10.56",
    "python-miio==0.5.12"
  ], `

To
` "requirements": [
    "construct",
    "python-miio"
  ], `

**Comment by sheminasalam** [comment]
> Just delete the version checks within manifest.json
> 
> From `"requirements": [ "construct==2.10.56", "python-miio==0.5.12" ],`
> 
> To `"requirements": [ "construct", "python-miio" ],`
> 
> #48

I can confirm that this works
